# Generated by Django 4.1.3 on 2022-12-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='Возраст')),
                ('salary', models.IntegerField(blank=True, default=0, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Человечки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Наименование')),
                ('flavour', models.CharField(default='', max_length=100, verbose_name='Вкус')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Ice Cream',
                'verbose_name_plural': 'Ice creams',
                'ordering': ('id',),
            },
        ),
    ]
