# Generated by Django 4.1.3 on 2022-12-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Child',
            new_name='Child_model',
        ),
    ]
