# Generated by Django 4.1.3 on 2022-12-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_rename_child_child_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='название')),
                ('location', models.CharField(default='', max_length=100, verbose_name='Местоположение')),
                ('rating', models.IntegerField(blank=True, default=0, verbose_name='рейтинг')),
                ('salary', models.IntegerField(blank=True, default=0, verbose_name='Прибыль')),
            ],
            options={
                'verbose_name': 'Kiosk',
                'verbose_name_plural': 'Kiosks',
                'ordering': ('id',),
            },
        ),
    ]
